### ISSUE TITLE
Can't run autocomplete route

### ISSUE THREAD

**Issue by Emirov** [mongodb-developer/beanie-example#2]
TypeError: AggregateInterface.aggregate() missing 1 required positional argument: 'aggregation_pipeline'

**Comment by Emirov** [comment]
I fixed that by using aggregation_pipeline instead of aggregation_query in the two routes cocktail_autocomplete and ingredients. However, I get an error with ingredients son.errors.InvalidDocument: cannot encode object: <class 'server.models.cocktail.IngredientAggregation'>, of type: <class 'pydantic.main.ModelMetaclass'> and the autocomplete return empty list despite I entered  a valid matching string

**Comment by judy2k** [comment]
`projection_model=IngredientAggregation,` is the key to fixing the encoding error! I've now fixed this in the repo.
